# Generated by Django 5.1.2 on 2025-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mymodel",
            name="css",
            field=models.TextField(default=""),
        ),
    ]
